#!/bin/bash

# This test file will be executed against after building a container with the
# 'latest' scenario in 'test/granted-cli/scenarios.json'.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# This test (as well as any of the other scenarios in 'scenarios.json') can be run with the following command:
#
#    devcontainer features test \ 
#               --features granted-cli \
#               --skip-autogenerated \
#               /path/to/this/repo

set -e

# Optional: Import test library bundled with the devcontainer CLI
# Provides the 'check' and 'reportResults' commands.
source dev-container-features-test-lib

# Feature-specific tests
# The 'check' command comes from the dev-container-features-test-lib.
check "Check granted is installed and can be run" bash -c "granted -v | grep 'Granted'"

# Report result
# If any of the checks above exited with a non-zero exit code, the test will fail.
reportResults
