#!/bin/bash

# This test file will be executed against after building a container with the
# 'pinned_version' scenario in 'test/granted-cli/scenarios.json'.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# This scenario first uses the 'common-utils' Features to add a new user 'testuser'. 
# It then installs the 'granted-cli' Feature with the VERSION option set to '0.36.0' (the default VERSION value if none provided is 'latest').
#
# This test (as well as any of the other scenarios in 'scenarios.json') can be run with the following command:
#
#    devcontainer features test \ 
#               --features granted-cli \
#               --skip-autogenerated \
#               /path/to/this/repo


set -e

# Optional: Import test library bundled with the devcontainer CLI
# Provides the 'check' and 'reportResults' commands.
source dev-container-features-test-lib

# Feature-specific tests
# The 'check' command comes from the dev-container-features-test-lib.
check "Check granted version is correct" bash -c "granted -v | grep '0.36.0'"

# Report result
# If any of the checks above exited with a non-zero exit code, the test will fail.
reportResults
